### ISSUE TITLE
do not generate flow file when there is no declare

### ISSUE THREAD

**Issue by budarin** [skovhus/css-modules-flow-types#13]
I have a .css file with only global classes - plugin generates declaration with empty state
```js
// @flow
/* This file is automatically generated by css-modules-flow-types */
declare module.exports: {|

|};
```
Maybe I'm wrong

**Comment by skovhus** [comment]
This is by design. Think about the following:
1) have a CSS files with multiple declarations, we generate a matching flow file
2) user removes css declarations


Would you 
A) generate an empty flow file (current behavior)
B) do nothing (suggested behavior in this ticket)

If you do nothing you end up with an invalid out of date flow file. 

Alternative is to remove the .flow file, but then we need to keep state... and I would really dislike that.

**Comment by budarin** [comment]
I agree - in project with CSS modules such styles must not be more than one or two - so there is nothing to worry.
